sudo: true
dist: trusty
services:
  - docker
language: python
python:
  - '3.5'
before_install:
  - "pip install 'lander>=0.1.0,<0.2'"
script:
  # Compile PDF using containerized lsst-texmf
  - "docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'"
  # Deploy website. See https://github.com/lsst-sqre/lander for CLI options
  - "lander --pdf LDM-612.pdf --upload --lsstdoc LDM-612.tex --env=travis --ltd-product ldm-612"
env:
  global:
    # LSST the Docs credentials
    - secure: "JLMSqQKWyMYrEBJkDP0bTq8FsfVOBYOCnGKvixmC8/7YT8VSANTxmkgF4W9LQMoVa63cr55ALuwGuKJyRziQCx+KyvdR+Pe9Vi681A+SKgdR+kWYTERyRaqyvirT1IAiZnmHbhFzFPdoP6vftce4Es6vAlYc9bSxkLEu5fN+vadQMco3Nnpvr88YTJS1R16mGiM6whrMh6c/gdkZOeRmoRZIf9QeaHIhw/ojb7U6wkGZL3m35tdb524VODklWWCmfob4ZAqNYEtI1kR1OBJ+hvZjnx+lX3dF6AKr4TzRe/7EFdfUZNyvVmPNaAIPs5PX9W7wQ5d27dRWkGof67pCsVADOOdJmhyHxURXOnFzA+xw4dcoHIZWqYFdEdPvaE5GO/J9JZWwJJyxijYMgbxrd3XBQqHwzMC6Ip5DDtQcZfiuIDuUR6tReTrZNxEcaFTwR5XtZnEj6Cz8c3hr14ZNc+O3kx6Tu43oVKhq6cA7ws5ON9E93hEl1792zzMy5B2fUHLWFLVc++jcAIrxMqyKVi64xXcNt2pnKUEaBxtN8+ZDwVRfXCGVgSh5hLLAvJ/J7Vxj+F6yonBa7lbojL7wE9aTgx4BxhAaMjz5k4XEiBDNQMP2JeQKN4oe5HojXTWGqcqicCjnO2l8BGv5PxifwfoZ4+oyJUWSDEEJAK+SF+s="
    - secure: "jDj6/6O2vGQydXHDQZzCMAsHR/riS87UdYLdA0xTG0voTlChbfXh4tCIz5n02wxXmLLHxJTW4c3HcKwYzFEep9xt5AesWr9vn7GRuBoI66DkbkwCApVbcGjEffWtx5qYPRQrfwPYJ1CqVHiVzjaFoY3p9/5jOgZoikTb+iZZIzQX5TSBa4bS9gBg1QStFJFiWM6fE1QzCEDsZUuVgvR0FFawie0lYLrQ+g2kjC5Yx09Z+13DMIIpKI4sZodRgaGtVuoJ/1Q3vV1LEi5qou20tbWd80W0MnpLShAP8c1CEaqo2o2OkdtVZFaV/D8bNe8GPel9NRWRiQnkX7ZqRZM88pJg70ZW3yfrN7rD2Jn12NMNZP6Ot9GSL4lj2ThS7rEiY1mA1lc3nyF022JwOgLl+GHua2ZfYISSS/YbYVm3pAPt6oSvXDbT5EJFupPvNYeY/eI3EeWY2b1Uxla3UbJzZhoYIWxRBqygUTqtPbexsoDjdZkDCqKF0Jmm1tzPXmeeT+GYzsNl/9FoKv3y0Ig7JijisaPx9ohAWnyvvpgX6CuncpKiBVJZrLYpH4IEhhIk3lBKb/foRgOdad7bsPZKSCYrWnzFYN8brwd2yQ6/MJtpKyKykoDfh6GI3YVrBMIQcu9t+dSTHdOKRBmHyk/fzXaaX3L5ploItg3GRpgT14Q="
